### ISSUE TITLE
BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by knifelees3** [ilyasku/jpkfile#1]
My jpk files are "xxx.jpk", and I want to read the jpk file via this module, I just use the following simple command
```
import jpkfile
 
jpk=jpkfile.JPKFile("./Data_JPK/QD655-09.jpk")
```
and I got the following error
```
  File "c:\program files\python38\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")

BadZipFile: File is not a zip file
```
it seems that the package can only handle the ".jpk-force" format not ".jpk" format?

**Comment by ilyasku** [comment]
Hi knifelees3,
main focus is on `jpk-force`. But the force maps `jpf-force-map` and optical tweezers `jpk-nt-force` should work as well. I have never encountered only `jpk` extensions, they are not used in our lab. 
From your error message, it looks like `jpk` is a totally different file format, that is not supported by my package. The other 3 are all `zip` files with the meta data easily readable. Do you have some information on the `jpk` format?

**Comment by knifelees3** [comment]
Hello ilyasku,

Thank you for your prompt reply! I'm not very familiar with the JPK format. I use the software from the company in the picture below

![image](https://user-images.githubusercontent.com/18129412/111470982-5e632500-8763-11eb-9f10-345c2b890f9e.png)

I noticed that if I directly run the command `zipfile.ZipFile('xxx.jpk')`, the same error happens and the main problem lies in the 'jpk' format. Just like you sad,  the 'jpk' file in our lab is not the same with `jpk-force` format. I also try to find some MATLAB program and I found the following package from [MATLAB File Exchange](https://www.mathworks.com/matlabcentral/fileexchange/68760-open_jpk)
and this program can't read our jpk files again. 
But I noticed that the program can really handle the 'jpk' format in the program
![image](https://user-images.githubusercontent.com/18129412/111471976-77200a80-8764-11eb-8c8e-8aa11638a41f.png)
So I'm very confused now. 
I want a python package to handle the JPK file or we need click and save the data into txt file by hand. I really hope that by making some minor changes and then your program can handle the 'jpk' file in our Lab. 
[QD655-10.zip](https://github.com/ilyasku/jpkfile/files/6156636/QD655-10.zip)
I attached the jpk file, can you help me see if this file can be read?

**Comment by ilyasku** [comment]
I tried to unzip your `.jpk`, but as we thought, it does not seem to be a zip file. It looks like it's some other binary file. Without some specifications on the file, it will not be easy to figure out the structure of the file.
Have you tried with multiple `.jpk` files? Does this one open in the jpk software? Or is it possible, that it's just this one file that is corrupt? Can you try that? 
Aside from that I am out of options. We would need some documentation from JPK on the file format to read it in python.

**Comment by ilyasku** [comment]
I checked the matlab code that you referenced, and it looks like the `.jpk` file holds single images or series of images.
I have no line numbers in the web view, but I think the relevant block starts with the line `if(strcmp(extension,valid_extensions{1,1}))` (which checks for matching `.jpk` extension). Looks like they simply get some info in the image file with imfinfo. That should also be possible in python with some image library.

**Comment by knifelees3** [comment]
The jpk files can all be opened by the jpk software including the files I attached to you, the jpk files store series of images and I can open the file in jpk software and select the image I want to export to txt data format. 
I think I need learn more about different jpk format and try to obtain the image information via some operations, just like you sad. 
Thank you for your kind and nice reply!
